services:
  redis:
    build: ./Redis
    ports:
      - "6378:6378"
    networks:
      - net

  # prometheus:
  #   build: ./Prometheus
  #   ports:
  #     - "9090:9090"
  #   depends_on:
  #     - user-backend
  #   networks:
  #     - net
  # prometheus:
  #   build: ./Prometheus
  #   ports:
  #     - "9090:9090"
  #   depends_on:
  #     - user-backend
  #   networks:
  #     - net
  
  # grafana:
  #   image: grafana/grafana-enterprise
  #   container_name: grafana
  #   restart: unless-stopped
  #   ports:
  #    - '3000:3000'
  #   networks:
  #     - net
  
  # node_exporter:
  #   image: quay.io/prometheus/node-exporter:latest
  #   container_name: node_exporter
  #   command:
  #     - '--path.rootfs=/host'
  #   pid: host
  #   restart: unless-stopped
  #   volumes:
  #     - '/:/host:ro,rslave'
  #   networks:
  #     - net

  ## ! CHANGE THE SCRIPT BEFORE PROD ! 
  vault:
    image: hashicorp/vault:1.21
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: >
      sh -c "
      vault server -dev &
      sleep 2 &&
      export VAULT_ADDR=http://127.0.0.1:8200 &&
      vault kv put secret/jwt jwt_secret=sua-chave-secreta &&
      tail -f /dev/null
      "
    restart: always
    cap_add:
      - IPC_LOCK
    depends_on:
      - user-backend
    networks:
      - net
  
  user-backend:
    build: ./src/User-Friends
    init: true
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/User-Friends:/app
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - net

  chat-backend:
    init: true
    build: ./src/Chat
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/Chat:/app
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - net

  game-backend:
    init: true
    build: ./src/GameTS #CHANGE BACK TO GAME WHEN DONE
    ports:
      - "8084:8084"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/GameTS:/app
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - net

  #nginx-modsecurity:
  #    build: ./nginx
  #    ports:
  #      - "8888:80"
  #      - "8443:8443"
  #    volumes:
  #      - ./src/Frontend:/usr/share/nginx/html:ro
  #      
  #    depends_on:
  #      - user-backend
  #      - chat-backend
  #    networks:
  #      - net

networks:
  net: